"""Default networking values for live training telemetry."""

DEFAULT_TRAINING_LIVE_HTTP_HOST = "127.0.0.1"
DEFAULT_TRAINING_LIVE_HTTP_PORT = 8774
DEFAULT_TRAINING_LIVE_WS_HOST = "127.0.0.1"
DEFAULT_TRAINING_LIVE_WS_PORT = 8775
