"""Shared environment constants."""

COMBAT_STATE_TYPES = {"monster", "elite", "boss"}
BATTLE_STATE_TYPES = COMBAT_STATE_TYPES | {"hand_select"}
BATTLE_REWARD_STATE_TYPES = {"rewards", "card_reward"}

BATTLE_WIN_REWARD = 1.0
BATTLE_LOSS_PENALTY = 1.0
BATTLE_ENEMY_DAMAGE_REWARD = 0.0
BATTLE_ENEMY_KILL_REWARD = 0.0
BATTLE_HP_LOSS_PENALTY = 0.02
BATTLE_POTION_USE_PENALTY = 0.05
BATTLE_UNUSED_ENERGY_PENALTY = 0.0
BATTLE_GOLD_LOSS_PENALTY = 0.005
BATTLE_MAX_HP_LOSS_PENALTY = 0.10

RUN_FLOOR_REWARD = 0.02
RUN_ACT_REWARD = 1.0
RUN_GAME_OVER_PENALTY = 1.0
