"""Shared environment constants."""

COMBAT_STATE_TYPES = {"monster", "elite", "boss"}
BATTLE_STATE_TYPES = COMBAT_STATE_TYPES | {"hand_select"}
BATTLE_REWARD_STATE_TYPES = {"rewards", "card_reward"}

BATTLE_WIN_REWARD = 100.0
BATTLE_LOSS_PENALTY = 100.0
BATTLE_ENEMY_DAMAGE_REWARD = 0.2
BATTLE_ENEMY_KILL_REWARD = 5.0
BATTLE_HP_LOSS_PENALTY = 2.0
BATTLE_POTION_USE_PENALTY = 1.0
BATTLE_UNUSED_ENERGY_PENALTY = 0.2
BATTLE_GOLD_LOSS_PENALTY = 0.1
BATTLE_MAX_HP_LOSS_PENALTY = 5.0
